### PR TITLE
49: Upgraded to version 3 of reuse action

### LINKED ISSUE #49: Upgrade license action to fsfe/reuse-action@v3
### Contact Details

_No response_

### What happened?

The License action is unable to run because the current version (v 1.0) is deprecated.

### Steps To Reproduce

- Run the license action

### What did you expect?

It is expected to fully run.

### Version

_No response_

### Optional Screenshots

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Ayko1595**
# Pull Request Description

Please include a summary of the change and which issue is fixed or added.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

Fixes #49 

## Checklist

- [x] Changes are limited to a single goal (avoid scope creep)
- [x] I confirm that I have read any Contribution and Development guidelines (CONTRIBUTING and DEVELOPMENT) and are following their suggestions.
- [x] I confirm that I wrote and/or have the right to submit the contents of my Pull Request, by agreeing to the _Developer Certificate of Origin_, (adding a 'sign-off' to my commits).

### CODE REVIEW

**Review by Philldomd — APPROVED** [review]

**Comment by Ayko1595** [comment]
@janderssonse Do you know why we are unable to run the reuse action in our workflow? The error message I am receiving seems to imply that we would need to create the reuse action ourselves.

> fsfe/reuse-action@v3.0.0 is not allowed to be used in diggsweden/jitsi-outlook. Actions in this workflow must be: within a repository owned by diggsweden, created by GitHub, or verified in the GitHub Marketplace.

**Comment by Philldomd** [comment]
Is this change needed? Seems lika a warning to me. The rest of the test was marked as green?

**Comment by Ayko1595** [comment]
@Philldomd Either this upgrade is needed or there is something else that is disturbing the actions. The last run that was successful was a week ago. I have been unable to start a new run because of the error that I mentioned in my last comment.

**Comment by janderssonse** [comment]
@Ayko1595 @Philldomd It is all my fault!  I restrained general security settings the other night for the organisation, as @Ayko1595 noted. Gimme two seconds I'll finetune a bit. Good catch to update it to v3!

**Comment by janderssonse** [comment]
Should be runnable now!

**Comment by Ayko1595** [comment]
@janderssonse Ahh perfect! No worries, and thanks for the quick fix 😄

**Pull request merged**
